In [15]:
import os

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
import json
import pickle
from keras.utils import np_utils
import matplotlib.pyplot as plt
import cv2
import pandas as pd

In [16]:
keras.backend.backend()

'theano'

In [17]:
# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train.shape

(60000, 28, 28)

In [18]:
# flatten 28*28 images to a 784 vector for each image
num_pixels = X_train.shape[1] * X_train.shape[2]
X_train = X_train.reshape(X_train.shape[0], num_pixels).astype('float32')
X_test = X_test.reshape(X_test.shape[0], num_pixels).astype('float32')

In [19]:
X_train.shape

(60000, 784)

In [20]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')


X_train shape: (60000, 784)
60000 train samples
10000 test samples


In [21]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)

num_classes = y_test.shape[1]


In [22]:

# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(num_pixels, input_dim=num_pixels, kernel_initializer='normal', activation='relu'))
    model.add(Dense(num_classes, kernel_initializer='normal', activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [23]:
X_train.shape, y_train.shape

((60000, 784), (60000, 10))

In [24]:
model = baseline_model()
# Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Baseline Error: %.2f%%" % (100-scores[1]*100))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 4s - loss: 0.2793 - acc: 0.9206 - val_loss: 0.1442 - val_acc: 0.9559
Epoch 2/10
 - 5s - loss: 0.1102 - acc: 0.9687 - val_loss: 0.0909 - val_acc: 0.9732
Epoch 3/10
 - 5s - loss: 0.0703 - acc: 0.9798 - val_loss: 0.0834 - val_acc: 0.9726
Epoch 4/10
 - 5s - loss: 0.0504 - acc: 0.9855 - val_loss: 0.0689 - val_acc: 0.9789
Epoch 5/10
 - 5s - loss: 0.0345 - acc: 0.9904 - val_loss: 0.0628 - val_acc: 0.9804
Epoch 6/10
 - 5s - loss: 0.0271 - acc: 0.9928 - val_loss: 0.0604 - val_acc: 0.9814
Epoch 7/10
 - 5s - loss: 0.0186 - acc: 0.9953 - val_loss: 0.0588 - val_acc: 0.9813
Epoch 8/10
 - 5s - loss: 0.0140 - acc: 0.9970 - val_loss: 0.0590 - val_acc: 0.9808
Epoch 9/10
 - 6s - loss: 0.0105 - acc: 0.9978 - val_loss: 0.0624 - val_acc: 0.9804
Epoch 10/10
 - 6s - loss: 0.0085 - acc: 0.9985 - val_loss: 0.0578 - val_acc: 0.9830
Baseline Error: 1.70%


In [25]:
pickle.dump(model, open('model.pkl','wb'))

In [26]:
X_train.shape

(60000, 784)

In [27]:
X_train[0:1].shape

(1, 784)

In [28]:
model.predict_classes(X_train[5:7])

array([2, 1])

In [29]:
X_train[0:1].shape

(1, 784)

In [30]:
img = cv2.imread("c2.jpeg", 0)
img = img.astype('float32')
img = img.astype('float32')
img /= 255
img=img.reshape(1,784)
model.predict_classes(img)

array([4])

In [31]:
img.shape

(1, 784)

In [32]:
a=X_train[6].reshape(1,784)
model.predict_classes(a)

array([1])

In [33]:
X_train[:9].shape

(9, 784)

In [34]:
img_resized.shape

NameError: name 'img_resized' is not defined

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

plt.imshow(X_train[9], cmap=plt.get_cmap('gray'))


In [ ]:
img = cv2.imread("c9.jpeg", 0)

In [ ]:
plt.imshow(img, cmap=plt.get_cmap('gray'))

In [ ]:
img-X_train[9]

In [ ]:
img = cv2.imread("1.jpeg", 0)

In [ ]:
img.shape

In [ ]:
img = cv2.resize(img,(28,28))

In [ ]:
plt.imshow(img, cmap=plt.get_cmap('gray'))

In [ ]:
img = img.astype('float32')
img = img.astype('float32')
img /= 255
img=img.reshape(1,784)
model.predict_classes(img)

In [ ]:
img = cv2.imread("c2.jpeg", 0)
img = img.astype('float32')
img = img.astype('float32')
img /= 255
img=img.reshape(1,784)
model.predict_classes(img)